[package]
name = "git-split-by-dir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.6.2"
tempfile = "3.8.1"
thiserror = "1.0.50"
crossterm = "0.25.0"
ratatui = "0.24.0"
anyhow = "1.0.75"
color-eyre = "0.6.2"
serde_json = "1.0.108"

[[example]]
name = "crossterm"

[[example]]
name = "hello_world"

[[example]]
name = "list"
